language: generic
services:
 - docker

# BE CAREFUL: There is a risk of outputting real credentials to logs here!
before_install:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker build -t platformoftrust/website:$TRAVIS_BUILD_NUMBER .

script:
 - docker push platformoftrust/website:$TRAVIS_BUILD_NUMBER
